2025-03-24 15:41:02,871 - ERROR - Attempt 1/3 failed: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
    at UIA2Proxy.command (C:\Users\hp\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:274:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at AndroidUiautomator2Driver.commands.getDevicePixelRatio (C:\Users\hp\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\commands\viewport.js:14:10)
    at AndroidUiautomator2Driver.fillDeviceDetails (C:\Users\hp\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:244:28)
    at AndroidUiautomator2Driver.createSession (C:\Users\hp\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:230:7)
    at AppiumDriver.createSession (C:\Users\hp\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\lib\appium.js:387:35)
2025-03-24 15:41:02,887 - INFO - Retrying in 5 seconds...
2025-03-24 15:41:07,889 - INFO - Checking if device is connected...
2025-03-24 15:41:07,934 - INFO - Attempting to connect to Appium server...
2025-03-24 15:41:18,088 - ERROR - Attempt 2/3 failed: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
    at UIA2Proxy.command (C:\Users\hp\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:274:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at AndroidUiautomator2Driver.commands.getDevicePixelRatio (C:\Users\hp\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\commands\viewport.js:14:10)
    at AndroidUiautomator2Driver.fillDeviceDetails (C:\Users\hp\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:244:28)
    at AndroidUiautomator2Driver.createSession (C:\Users\hp\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:230:7)
    at AppiumDriver.createSession (C:\Users\hp\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\lib\appium.js:387:35)
2025-03-24 15:41:18,089 - INFO - Retrying in 5 seconds...
2025-03-24 15:41:22,166 - INFO - Program execution completed
2025-03-24 15:42:29,199 - INFO - Checking if device is connected...
2025-03-24 15:43:09,206 - INFO - Checking if device is connected...
2025-03-24 15:45:21,174 - INFO - Checking if device is connected...
2025-03-24 15:45:23,318 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000199EE54F940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session
2025-03-24 15:45:25,374 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000199EE54FB20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session
2025-03-24 15:45:27,428 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000199EE54FD90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session
2025-03-24 15:50:43,160 - INFO - Checking if device is connected...
2025-03-24 15:52:33,397 - INFO - Checking if device is connected...
2025-03-24 15:53:04,920 - INFO - Attempting to locate element: search_explore
2025-03-24 15:53:10,568 - INFO - Successfully located element: search_explore
2025-03-24 15:53:10,796 - INFO - Successfully clicked search_explore
